#!/usr/bin/ruby
# encoding: utf-8

require 'thor'
require 'rainbow'
require_relative 'lib/exec_manager'
require_relative 'lib/settings'

# Command Line User Interface
class Freya < Thor

  map ['h', '-h', '--help'] => 'help'

  map ['s', '-s', '--show'] => 'show'
    desc 'show INFO from HOSTS', 'Show information INFO from specific HOSTS'
    option :c, :type => :boolean
    long_desc <<-LONGDESC

  LONGDESC
  def show(command, from=:from, hosts)
    ExecManager.new(command, hosts).run
  end

  map ['v', '-v', '--version'] => 'version'
  desc 'version', 'Show the program version'
  def version
    s = Settings.instance
    print Rainbow(s.name).bright.blue
    puts  ' (version ' + Rainbow(s.version).green + ')'
  end

  def method_missing(m, *_args, &_block)
    help #play(m.to_s)
  end

  def respond_to_missing?(method_name, include_private = false)
    super
  end
end

Freya.start(ARGV)
