#!/usr/bin/env ruby
# File: mmcc (My Modern C compiler)

NAME="ncc"

if ARGV.empty? || ARGV.first == '--help'
  puts "Usage: #{NAME} [options] file..."
  puts "Options:"
  puts "  --help                   Display this information."
  puts "  --version                Display compiler version information."
  exit 0
elsif ARGV.first == '--version'
  puts "#{NAME} (GNU/Linux) 0.1.0 20251221"
  puts "Copyright (C) 2025 Free Software Foundation, Inc."
  puts "This is free software; see the source for copying conditions.  There is NO"
  puts "warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE."
  exit 0
end

filename = ARGV.first
lines = File.readlines(filename, chomp: true)
lines.insert(0, "#!/usr/bin/env ruby")
lines.insert(1, 'require_relative "modern/c"')

File.open('a.out', 'w') do |file|
  file.puts(lines)
end

system("chmod +x ./a.out")
