# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in space_invaders.gemspec
gemspec

gem "rake", "~> 13.0"
gem "test-unit", "~> 3.0"
gem "standard", "~> 1.3"
gem "curses"
