#!/usr/bin/ruby

require 'rainbow'

print "¡Hola! ¿Cómo te llamas? "
username = Rainbow(gets.capitalize.chop).blue.bright

print "Level (1-9)? "
level = gets.to_i 

points = { ok: 0, fail: 0}
max = 10

puts "===================================================="
puts "Comienza el juego"
puts "Tienes que responder correctamente a #{max} retos."
puts "¡Mucha suerte!"
puts "===================================================="

time_start = Time.now

(1..max).each do |i| 
  #puts "Reto número #{Rainbow(i).bright} de #{Rainbow(max).bright}"
  op1 = rand(level)+1
  op2 = rand(max)+1
  val = op1 * op2
  if rand()<=0.5
    print "Reto ->  #{op1} x #{op2} = "
  else
    print "Reto ->  #{op2} x #{op1} = "
  end
  res = gets.to_i
  if res == val 
    points[:ok] += 1
    puts Rainbow("        ¡Muy bien!").green
  else
    points[:fail] += 1
    puts Rainbow("        #{username}, el valor correcto es ").red + Rainbow(val).red.bright
  end
end

time_interval = (Time.now - time_start).to_i

puts "===================================================="
puts "Has acertado #{points[:ok]}, y"
puts "has fallado  #{points[:fail]}."
puts "#{username}, tu puntuación final es #{Rainbow((100*points[:ok]/max).to_i).yellow.bright}%."
puts "Tiempo #{Rainbow(time_interval).yellow.bright}"
puts "===================================================="
